# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simplesim_rcpp <- function(ss, sites, rec, growthmod) {
    .Call('ARG_simplesim_rcpp', PACKAGE = 'ARG', ss, sites, rec, growthmod)
}

treeheight <- function(ptr) {
    .Call('ARG_treeheight', PACKAGE = 'ARG', ptr)
}

