# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simplesim <- function(ss, sites, rec, growthmod) {
    .Call('ARG_simplesim', PACKAGE = 'ARG', ss, sites, rec, growthmod)
}

mmsim <- function(location, sites, rec, growthmod, migmodel) {
    .Call('ARG_mmsim', PACKAGE = 'ARG', location, sites, rec, growthmod, migmodel)
}

treeheight <- function(ptr) {
    .Call('ARG_treeheight', PACKAGE = 'ARG', ptr)
}

treelength <- function(ptr) {
    .Call('ARG_treelength', PACKAGE = 'ARG', ptr)
}

mutate <- function(ptr, var, ascert = "panel(3)") {
    .Call('ARG_mutate', PACKAGE = 'ARG', ptr, var, ascert)
}

TMRCA <- function(graph, position, samps) {
    .Call('ARG_TMRCA', PACKAGE = 'ARG', graph, position, samps)
}

pruneARG <- function(ptr, samples) {
    invisible(.Call('ARG_pruneARG', PACKAGE = 'ARG', ptr, samples))
}

